services:
  - type: web
    name: school-site
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1